import type { Metadata } from "next";
import { Karla } from 'next/font/google'

const karla = Karla({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-karla',
  display: 'swap',
})

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={karla.variable}>
      <body className="flex items-center justify-center min-h-screen">
        {children}
      </body>
    </html>
  );
}
